version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-static-site
    ports:
      - "8080:80"  # 将容器的 80 端口映射到本地的 8080 端口
    volumes:
      - ./:/usr/share/nginx/html  # 将本地的 static-site 目录挂载到容器的 /usr/share/nginx/html 目录
    networks:
      - nginx-network
    restart: always

networks:
  nginx-network:
    driver: bridge
